name: cd
run-name: Pulling image to server
on: [push]
  # push:
  #   branches:
  #     - 'main'
jobs:
  deploy-new-image:
    runs-on: ubuntu-latest
    steps:
      - run: echo "SSH into Droplet"
      - name: Login to Droplet
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "hi in server"
            docker pull nikitasreenath/niki-saunak:b58ea9d4cdae795553598ce61cf04468baec4e5d
            docker rm -f $(docker ps -a -q) 
            docker run -d --restart unless-stopped -p 8080:80 niki-saunak